### ISSUE TITLE
Try to avoid using too many tag selectors in css

### ISSUE THREAD

**Issue by ko-karol** [fac26/Dominic-Gareth-Markup-Project#23]
```css
* {
    box-sizing: border-box;
    margin: 0;
  }

  html {
    font-size: var(--fs);
    font-family: Arial, Helvetica, sans-serif;
    letter-spacing: var(--letter-spacing);
  }
  
  body {
    max-width: 90vw;
    margin-left: auto;
    margin-right: auto;
    background-color: #eee8e8;
    margin-bottom: 20px;
  }
  
  a {
    text-decoration: none;
    color: inherit;
  }
  
  ul {
    list-style: none;
    padding: 0;
  }
  
  img {
    display: block;
    max-width: 100%;
    height: auto;
  }
```
try reusable classes instead of specific tags. Too much specificity is not great.

```css
.list-item {}
.list-image {}
```
etc etc
